In [1]:
# import the libraries
import pandas as pd
import numpy as np

In [2]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_eb4ca40d8e9b4b39a3d2bdd7be92f861 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='kFhmeg6fhpGHn2vnjfGnCeysb94ozYrF9bShlHgCbvG3',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

body = client_eb4ca40d8e9b4b39a3d2bdd7be92f861.get_object(Bucket='custommodel-donotdelete-pr-wsxkamrco5y23o',Key='Churn_Modelling.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

dataset = pd.read_csv(body)
dataset.head()


RowNumber  CustomerId   Surname  CreditScore Geography  Gender   Age  \
0          1    15634602  Hargrave        619.0    France  Female   NaN   
1          2    15647311      Hill        225.0     Spain  Female  41.0   
2          3    15619304      Onio        629.0    France     NaN  42.0   
3          4    15701354      Boni        699.0    France  Female  39.0   
4          5    15737888  Mitchell        850.0     Spain  Female  43.0   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
type(dataset)

pandas.core.frame.DataFrame

In [4]:
dataset.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore         True
Geography          False
Gender              True
Age                 True
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [5]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender   Age  \
0          1    15634602  Hargrave        619.0    France  Female   NaN   
1          2    15647311      Hill        225.0     Spain  Female  41.0   
2          3    15619304      Onio        629.0    France     NaN  42.0   
3          4    15701354      Boni        699.0    France  Female  39.0   
4          5    15737888  Mitchell        850.0     Spain  Female  43.0   
5          6    15574012       Chu          NaN     Spain    Male  44.0   
6          7    15592531  Bartlett        619.0    France    Male  50.0   
7          8    15656148    Obinna        376.0   Germany  Female  29.0   
8          9    15792365        He        501.0    France    Male  44.0   
9         10    15592389        H?        684.0    France    Male  43.0   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [6]:
dataset['Gender'].fillna(dataset['Gender'].mode()[0],inplace = True)
dataset['Age'].fillna(dataset['Age'].mean(),inplace = True)
dataset['CreditScore'].fillna(dataset['CreditScore'].median(),inplace = True)

In [7]:
dataset.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [8]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender        Age  \
0          1    15634602  Hargrave        619.0    France  Female  38.923092   
1          2    15647311      Hill        225.0     Spain  Female  41.000000   
2          3    15619304      Onio        629.0    France    Male  42.000000   
3          4    15701354      Boni        699.0    France  Female  39.000000   
4          5    15737888  Mitchell        850.0     Spain  Female  43.000000   
5          6    15574012       Chu        652.0     Spain    Male  44.000000   
6          7    15592531  Bartlett        619.0    France    Male  50.000000   
7          8    15656148    Obinna        376.0   Germany  Female  29.000000   
8          9    15792365        He        501.0    France    Male  44.000000   
9         10    15592389        H?        684.0    France    Male  43.000000   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset["Geography"] = le.fit_transform(dataset["Geography"])


In [10]:
dataset["Gender"] = le.fit_transform(dataset["Gender"])

In [11]:
#x = dataset["rows",columns].values
x = dataset.iloc[:,3:13].values #inputs
y = dataset.iloc[:,13].values #output

In [12]:
dataset

RowNumber  CustomerId    Surname  CreditScore  Geography  Gender  \
0             1    15634602   Hargrave        619.0          0       0   
1             2    15647311       Hill        225.0          2       0   
2             3    15619304       Onio        629.0          0       1   
3             4    15701354       Boni        699.0          0       0   
4             5    15737888   Mitchell        850.0          2       0   
...         ...         ...        ...          ...        ...     ...   
9995       9996    15606229   Obijiaku        771.0          0       1   
9996       9997    15569892  Johnstone        516.0          0       1   
9997       9998    15584532        Liu        709.0          0       0   
9998       9999    15682355  Sabbatini        772.0          1       1   
9999      10000    15628319     Walker        792.0          0       0   

            Age  Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0     38.923092       2       0.00              1          1               1   
1     41.000000       1   83807.86              1          0               1   
2     42.000000       8  159660.80              3          1               0   
3     39.000000       1       0.00              2          0               0   
4     43.000000       2  125510.82              1          1               1   
...         ...     ...        ...            ...        ...             ...   
9995  39.000000       5       0.00              2          1               0   
9996  35.000000      10   57369.61              1          1               1   
9997  36.000000       7       0.00              1          0               1   
9998  42.000000       3   75075.31              2          1               0   
9999  28.000000       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [13]:
x

array([[6.1900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [2.2500000e+02, 2.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [6.2900000e+02, 0.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [14]:
x

array([[6.1900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [2.2500000e+02, 2.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [6.2900000e+02, 0.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [15]:
from sklearn.preprocessing import OneHotEncoder
one =  OneHotEncoder()
z = one.fit_transform(x[:,1:2]).toarray()
x = np.delete(x,1,axis = 1)
x = np.concatenate((z,x),axis = 1)

In [16]:
z

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [17]:
x

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)

In [19]:
x.shape

(10000, 12)

In [20]:
x_train.shape


(8000, 12)

In [21]:
x_test.shape
#female -0



(2000, 12)

In [22]:
from sklearn.model_selection import train_test_split
x1 = [1,2,3,4,5,6,7,8,9,10]
y1 = [1,0,1,0,1,0,1,0,1,0,]
for i in range(5):
    x_train1,x_test1,y_train1,y_test1 = train_test_split(x1,y1,test_size = 0.2,random_state = 2)
    print(x_train1 , "with random state")

[6, 1, 8, 3, 4, 7, 10, 9] with random state
[6, 1, 8, 3, 4, 7, 10, 9] with random state
[6, 1, 8, 3, 4, 7, 10, 9] with random state
[6, 1, 8, 3, 4, 7, 10, 9] with random state
[6, 1, 8, 3, 4, 7, 10, 9] with random state


In [23]:
for i in range(5):
    x_train1,x_test1,y_train1,y_test1 = train_test_split(x1,y1,test_size = 0.2)
    print(x_train1, "without random state")

[5, 6, 9, 2, 8, 3, 4, 10] without random state
[8, 7, 3, 9, 1, 4, 10, 5] without random state
[7, 3, 8, 10, 1, 6, 4, 5] without random state
[5, 2, 6, 3, 9, 8, 4, 7] without random state
[3, 8, 7, 1, 4, 9, 10, 2] without random state


In [24]:
from sklearn.ensemble import RandomForestClassifier
forest_reg = RandomForestClassifier(n_estimators=10, criterion='entropy',random_state=42)
forest_reg.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=42)

In [25]:
x_train[0]

array([1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.8600000e+02,
       1.0000000e+00, 3.2000000e+01, 6.0000000e+00, 0.0000000e+00,
       2.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.7909326e+05])

In [36]:
from ibm_watson_machine_learning import APIClient
wml_credentials = {
                   "url": "https://us-south.ml.cloud.ibm.com",
                   "apikey":"zd8zC6MNUD17UV5o0Ej9JZsgt5cMMq14E-23FQKjOoO5"
                  }

client = APIClient(wml_credentials)

In [37]:
def guid_from_space_name(client, space_name):
    space = client.spaces.get_details()
    #print(space)
    return(next(item for item in space['resources'] if item['entity']["name"] == space_name)['metadata']['id'])

In [28]:
space_uid = guid_from_space_name(client, 'Newspace')
print("Space UID = " + space_uid)

Space UID = 629361d6-9d68-4d27-a2f8-796d0e4ed536


In [29]:
client.set.default_space(space_uid)

'SUCCESS'

In [30]:
client.software_specifications.list()

-----------------------------  ------------------------------------  ----
NAME                           ASSET_ID                              TYPE
default_py3.6                  0062b8c9-8b7d-44a0-a9b9-46c416adcbd9  base
pytorch-onnx_1.3-py3.7-edt     069ea134-3346-5748-b513-49120e15d288  base
scikit-learn_0.20-py3.6        09c5a1d0-9c1e-4473-a344-eb7b665ff687  base
spark-mllib_3.0-scala_2.12     09f4cff0-90a7-5899-b9ed-1ef348aebdee  base
ai-function_0.1-py3.6          0cdb0f1e-5376-4f4d-92dd-da3b69aa9bda  base
shiny-r3.6                     0e6e79df-875e-4f24-8ae9-62dcc2148306  base
pytorch_1.1-py3.6              10ac12d6-6b30-4ccd-8392-3e922c096a92  base
tensorflow_1.15-py3.6-ddl      111e41b3-de2d-5422-a4d6-bf776828c4b7  base
scikit-learn_0.22-py3.6        154010fa-5b3b-4ac1-82af-4d5ee5abbc85  base
default_r3.6                   1b70aec3-ab34-4b87-8aa0-a4a3c8296a36  base
pytorch-onnx_1.3-py3.6         1bc6029a-cc97-56da-b8e0-39c3880dbbe7  base
tensorflow_2.1-py3.6           1eb25b8

In [31]:
software_spec_uid = client.software_specifications.get_uid_by_name("default_py3.7")
software_spec_uid

'e4429883-c883-42b6-87a8-f419d64088cd'

In [32]:
 model_details = client.repository.store_model(model=forest_reg,meta_props={
 client.repository.ModelMetaNames.NAME:"Churn_modeling",
 client.repository.ModelMetaNames.TYPE:"scikit-learn_0.23",
 client.repository.ModelMetaNames.SOFTWARE_SPEC_UID:software_spec_uid }
                                          )
model_id = client.repository.get_model_uid(model_details)

In [33]:
model_id

'def3a49f-557c-459d-82dc-e72e671da996'

In [34]:
x_train[0]

array([1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.8600000e+02,
       1.0000000e+00, 3.2000000e+01, 6.0000000e+00, 0.0000000e+00,
       2.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.7909326e+05])

In [35]:
forest_reg.predict([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.8600000e+02,
       1.0000000e+00, 3.2000000e+01, 6.0000000e+00, 0.0000000e+00,
       2.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.7909326e+0]])

array([0])